# Generated by Django 5.2.8 on 2025-11-07 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve conter exatamente 11 dígitos numéricos', regex='^\\d{11}$')])),
                ('nome_completo', models.CharField(max_length=150)),
                ('data_nascimento', models.DateField()),
                ('rg', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=150)),
                ('telefone_principal', models.CharField(max_length=15)),
                ('cep', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='CEP deve conter exatamente 8 dígitos numéricos', regex='^\\d{8}$')])),
                ('logradouro', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=80)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('pais', models.CharField(default='Brasil', max_length=50)),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Pessoa Física',
                'verbose_name_plural': 'Pessoas Físicas',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ deve conter exatamente 14 dígitos numéricos', regex='^\\d{14}$')])),
                ('razao_social', models.CharField(max_length=150)),
                ('nome_fantasia', models.CharField(max_length=150)),
                ('data_abertura', models.DateField()),
                ('email_comercial', models.EmailField(max_length=150)),
                ('telefone_principal', models.CharField(max_length=15)),
                ('inscricao_estadual', models.CharField(max_length=20)),
                ('site', models.URLField(blank=True, max_length=150, null=True)),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('logradouro', models.CharField(max_length=150)),
                ('bairro', models.CharField(max_length=80)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('numero', models.CharField(max_length=10)),
                ('pais', models.CharField(default='Brasil', max_length=50)),
            ],
            options={
                'verbose_name': 'Pessoa Jurídica',
                'verbose_name_plural': 'Pessoas Jurídicas',
                'ordering': ['razao_social'],
            },
        ),
    ]
